#!/bin/bash 
#cd /home/salvador/github/watchman-readout/PCsoftware
#channel=$2
totalWindows=$nofPackets
nofWindowsStep=1
nofAmplStep=1
nofTARGETs=2
nofChannels=16
nofwindows=10
nofpackets=2*$nofwindows #32
file_name="/home/salvador/github/watchman-readout/PCsoftware/traffic.pcap"

tcpdump -ni enx0050b67c1322 udp port 8 -w  $file_name -c 20 &>packets.log &    #-s 2054   

# TO capture the fragmented packets use the filter & double the count parameter. No udp port info (if added, will give syntax error)
# use test_analysis.py instead of pulse_analysis.py in listenPacketsTrig.py file
#tcpdump -ni enx0050b67c1322 '(ip[6:2] > 0) and (not ip[6] == 64)' -w  $file_name -c 4 &>packets.log &

#python3.8 listenPacketsTrig.py $nofPackets $totalWindows $nofChannels&> packets.log &

python3 HMBtriggerMode.py &>triggercmd.log &

sleep 15


python3 listenPacketsTrig.py $file_name $nofwindows    #$nofpackets

