#!/usr/bin/env bash

connect() {
        if [ $(ls /dev/ttyUSB0 | wc -l) = "1" ]; then
                echo picocom -b 115200 /dev/ttyUSB0
                sudo picocom -b 115200 /dev/ttyUSB0 | tee watchmanLog.txt
        elif [ $(ls /dev/ttyUSB0 | wc -l) = "1" ]; then
                echo picocom -b 115200 /dev/ttyUSB1
                sudo picocom -b 115200 /dev/ttyUSB1 | tee watchmanLog.txt
        else
                echo picocom -b 115200 /dev/ttyUSB2
                sudo picocom -b 115200 /dev/ttyUSB2| tee watchmanLog.txt            
        fi  
}
echo "Usage: $0 {log|picocom}";
connect


